"""Add User model and Auth

Revision ID: 1228e6887efa
Revises: a1430ac54536
Create Date: 2026-03-11 17:38:48.001759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1228e6887efa'
down_revision: Union[str, Sequence[str], None] = 'a1430ac54536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('scenes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='scenestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scenes_created_at', 'scenes', ['created_at'], unique=False)
    op.create_index(op.f('ix_scenes_user_id'), 'scenes', ['user_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scene_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.Enum('narrative', 'visual', 'soundtrack', name='assettype'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='assetstatus'), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('artifact_path', sa.String(length=512), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_scene_id'), 'assets', ['scene_id'], unique=False)
    op.create_index('ix_assets_scene_type', 'assets', ['scene_id', 'asset_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assets_scene_type', table_name='assets')
    op.drop_index(op.f('ix_assets_scene_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_scenes_user_id'), table_name='scenes')
    op.drop_index('ix_scenes_created_at', table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
